spring:
  application:
    name: jwt
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: admin
    password: ""


roles:
  user: USER
  admin: ADMIN

key: "295206998413d3296653b590de7d8db835d7d082e6130a718b435dde63ea5298"
logging:
  level:
    com:
      uexcel: debug

management:
  info:
    env:
      enabled: true

info:
  name: jwt
  description: "JWT Demo"
  version: v1
